[build]
  base = "frontend"
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"
  
[context.production.environment]
  NETLIFY_BUILD_IMAGE = "focal"
